version: '3'
services:
  local-db:
    image: mysql:8.2.0
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classting_homework
      TZ: Asia/Seoul
